include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    deprecated_member_use: error
  exclude:
    - build/**
    - android/**
    - ios/**
    - test/generated_migrations/**

plugins:
  riverpod_lint: 3.1.9
